Adding API endpoints
Gaz492/TwitchAPI pull request #1
Opened 2019-07-08 05:27 UTC by TOLoneWolf

Added The following Endpoints:
GET	https://addons-ecs.forgesvc.net/api/v2/minecraft/version
GET	https://addons-ecs.forgesvc.net/api/v2/minecraft/version/timestamp
GET	https://addons-ecs.forgesvc.net/api/v2/minecraft/modloader
GET	https://addons-ecs.forgesvc.net/api/v2/minecraft/modloader/timestamp
GET	https://addons-ecs.forgesvc.net/api/v2/minecraft/modloader/{VersionName}
GET	https://addons-ecs.forgesvc.net/api/v2/category
GET	https://addons-ecs.forgesvc.net/api/v2/category/timestamp
GET	https://addons-ecs.forgesvc.net/api/v2/game
GET	https://addons-ecs.forgesvc.net/api/v2/game/timestamp

I haven't used "API Blueprint" format before so I hope I have everything correctly formatted. Wasn't sure if tab/spacing matters.
Didn't see an easily accessible editor/Validator.

2019-07-08 21:26 UTC, Franckyi commented
There's also :
GET https://addons-ecs.forgesvc.net/api/v2/minecraft/version/{versionString}

2019-07-09 17:25 UTC, skyecodes requested changes
There are a few typos left.

2019-07-09 17:25 UTC, Franckyi commented on apiary.apib
> +## Get Category Info [/api/v2/v2/category/{Categoryid}]
```suggestion
## Get Category Info [/api/v2/category/{Categoryid}]
```

2019-07-09 17:25 UTC, Franckyi commented on apiary.apib
> +## Get Game Info [/api/v2/v2/game/{GameID}]
```suggestion
## Get Game Info [/api/v2/game/{GameID}]
```

2019-07-09 19:35 UTC, TOLoneWolf commented
Thanks Franckyi for pointing those out.

I noticed some of the parameters where not getting highlighted right (using sublimetext3), (integer) is the type currently there but in the documentation for API Blueprint it shows (number) as the correct type.
https://apiblueprint.org/documentation/specification.html
Just want to make sure that is correct before changing those since I am new to the API Blueprint formatting and not sure if apiary follows that specification.

2019-07-14 17:51 UTC, merged

2019-07-14 18:03 UTC, Gaz95 commented
A simple way of checking if something is correct is to use https://apiary.io